# Copyright (c) 2023-2024, The MyFamily Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

schedules:
- cron: "0 7 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main
  always: true

trigger:
  branches:
    include:
      - main
  tags:
    include: ['*']

pr:
  branches:
    include: ['*']

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      all:
        CI_JOB: all
        PLATFORM: linux-amd64
  steps:
    - script: |
        uname -a
        sudo apt-get update
        sudo apt-get install libcriterion-dev doxygen
        sudo apt-get install python3-pip
        sudo pip3 install pre-commit
      displayName: Linux Test Dependencies
    - template: '.ci/all.yml'
- job: macos
  pool:
    vmImage: macOS-latest
  strategy:
    matrix:
      all:
        CI_JOB: all
        PLATFORM: macos
  steps:
    - script: |
        sw_vers
        brew install criterion
        brew install python
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install pre-commit
        pre-commit install
        pre-commit run --all-files
      displayName: MacOS Test Dependencies
    - template: '.ci/all.yml'
