include ../Makefile.config
SOURCES := $(patsubst %.c,%.o,$(wildcard *.c))

%.o : %.c $(HEADERS)
	$(CC) $(CC_FLAGS) -c -o $@ $<
all: $(OBJS)
test: test.c
	mkdir -p bin
	rm -rf bin/test
	$(CC) $(CC_TEST_FLAGS) $(TEST_OBJS) -o bin/test test.c
	./bin/test --timeout 10 -f
	rm -rf bin
clean:
	rm -rf *.o
	rm -rf bin
	rm -rf *.gcov
	rm -rf *.gcno
	rm -rf *.gcda
