CC=gcc
CC_FLAGS=-I.. $(COVERAGE)
CC_TEST_FLAGS=-lcriterion -L/Users/christophergilliard/homebrew/Cellar/criterion/2.4.2/lib -I/Users/christophergilliard/homebrew/Cellar/criterion/2.4.2/include -I.. $(COVERAGE)
MAKE=make
SUBDIRS := main parser util
ALL_OBJS=main/*.o parser/*.o util/*.o
HEADERS := $(wildcard *.h) $(wildcard parser/*.h) $(wildcard util/*.h)
