OBJS := heap.o \
	panic.o \
	chain_allocator.o \
	lock.o \
	thread.o \
	prim.o \
	type.o \
	traits.o \
	rc.o \
	unit.o \
	backtrace.o

TEST_OBJS := $(OBJS) test_encapsulation.o test_server.o

include ../Makefile.template
