OBJS := class.o \
	enum.o \
	tuple.o \
	panic.o \
	resources.o \
	traits.o \
	unit.o \
	prim.o \
	rc.o \
	backtrace.o \
	error.o \
	string.o \
	formatter.o \
	format.o \
	rand.o \
	string_builder.o \
	io.o \
	file.o \
	iterator.o \
	buf_reader.o
TEST_OBJS := $(OBJS)

include ../Makefile.template
