OBJS := rand.o \
	slabs.o \
	mymalloc.o \
	class.o \
	rc.o \
	traits.o \
	unit.o \
	prim.o \
	backtrace.o \
	error.o \
	panic.o \
	string.o \
	slice.o \
	string_builder.o \
	tuple.o \
	formatter.o

TEST_OBJS := $(OBJS)

include ../Makefile.template
