CC=gcc
CC_FLAGS = 
SOURCES := $(patsubst %.c,%.o,$(wildcard *.c))
HEADERS := $(wildcard *.h)
OBJS := test.o\
	util.o

%.o : %.c $(HEADERS)
	$(CC) $(CCFLAGS) -c -o $@ $<
all: $(OBJS)
clean:
	rm -rf *.o
