# Package details
[package]
	name = "fam_core"
	version = "0.0.1-beta.1"
	authors = ["The MyFamily Developers"]
	description = "core - My Family core libraries"
	keywords = ["Jesus", "Bible", "Family", "Crypto"]

[dependencies]
	fam_util = { path = "../util" }

