fam_version = "REPLACE_FAM_VERSION"

[package]
name = "REPLACE_NAME"
version = "0.0.1"
authors = [REPLACE_AUTHORS]
description = "REPLACE_DESCRIPTION"
lib = true

[dependencies]

[test-dependencies]

