OBJS := panic.o tlmalloc.o backtrace.o class.o traits.o prim.o string.o unit.o error.o result.o rc.o option.o rand.o tokenizer.o formatter.o tuple.o io.o file.o
TEST_OBJS := $(OBJS)

include ../Makefile.template
