name: CI Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 7 * * *" # Daily midnight build

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-amd64]
    steps:
      - name: Check uname
        run: uname -a
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcriterion-dev doxygen python3-pip
          sudo pip3 install pre-commit
      
      - name: Run Linux Tests
        run: |
          ./ci/all.sh
          
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [macos]
    steps:
      - name: Check macOS Version
        run: sw_vers
      
      - name: Install dependencies
        run: |
          brew install criterion
          python3 -m venv venv
          source venv/bin/activate
          # pip install pre-commit
          # pre-commit install
      
      - name: Run MacOS Tests
        run: |
          ./ci/all.sh

