name: CI Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "15 7 * * *" # Daily midnight build (15 after)
  workflow_dispatch:  # This enables manual triggering

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check uname
        run: uname -a
      
      - name: Test Linux Build
        run: |
          # ./configure --minimal
          # make clean all -s
          # ./bin/fam init test1
          # test -d ~/.fam/resources || { echo "Error: ~/.fam/resources directory does not exist"; exit 1; }

      - name: Install Test dependencies
        run: |
          # sudo apt-get update
          # sudo apt-get install libcriterion-dev doxygen python3-pip
          # sudo pip3 install pre-commit

      - name: Run Linux Tests (gcc)
        run: |
          ./fam test
      
      - name: Run Linux Tests (clang)
        run: |
          # ./configure --with-cc=clang
          # make clean testsannc -s

      - name: Build Docs
        run: |
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [macos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check macOS Version
        run: sw_vers
      
      - name: Test MacOS Build
        run: |
          # ./scripts/configure_homebrew.sh --minimal
          # make clean all
          # ./bin/fam init test1
          # test -d ~/.fam/resources || { echo "Error: ~/.fam/resources directory does not exist"; exit 1; }

      - name: Install dependencies
        run: |
          # brew install criterion
          # python3 -m venv venv
          # source venv/bin/activate
          # pip install pre-commit
          # pre-commit install
     
      - name: Run MacOS Tests (gcc)
        run: |
          ./fam test
      
      - name: Run MacOS Tests (clang)
        run: |
          # ./scripts/configure_homebrew.sh --with-cc=clang
          # make clean testsan -s
