name: CI Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "49 5 * * *" # Daily midnight build
  workflow_dispatch:  # This enables manual triggering

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check uname
        run: uname -a
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcriterion-dev doxygen python3-pip
          sudo pip3 install pre-commit
      
      - name: Run Linux Tests
        run: |
          ./configure
          make clean all
          ./bin/fam init test1
          test -d ~/.fam/resources || { echo "Error: ~/.fam/resources directory does not exist"; exit 1; }
          make clean testsan
          # Build documentation for Linux only when the pipeline is triggered manually or on schedule
          if [[ "$GITHUB_EVENT_NAME" == "schedule" || "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            echo "running build docs";
            ./scripts/build_docs.sh "${{ secrets.MyFamilyPat }}" "$GITHUB_SHA"
          else
            echo "not running build docs event: $GITHUB_EVENT_NAME";
          fi          
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [macos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check macOS Version
        run: sw_vers
      
      - name: Install dependencies
        run: |
          brew install criterion
          python3 -m venv venv
          source venv/bin/activate
          # pip install pre-commit
          # pre-commit install
      
      - name: Run MacOS Tests
        run: |
          ./scripts/configure_homebrew.sh
          make clean all
          ./bin/fam init test1
          test -d ~/.fam/resources || { echo "Error: ~/.fam/resources directory does not exist"; exit 1; }
          make clean testsan
