name: CI Pipeline
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "15 7 * * *" # Daily midnight build (15 after)
  workflow_dispatch:  # This enables manual triggering

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check uname
        run: uname -a
      
      - name: Test Linux Build
        run: |
           ./fam clean; ./fam
           # test -d ~/.fam/resources || { echo "Error: ~/.fam/resources directory does not exist"; exit 1; }
      - name: Run Linux Tests (gcc)
        run: |
          ./fam clean; ./fam test --with-cc=gcc -s
      - name: Run Linux Tests (clang)
        run: |
          ./fam clean; ./fam test --with-cc=clang -s
      - name: Build Docs
        run: |
          echo "evt=$GITHUB_EVENT_NAME";
          git clone https://anything:${{ secrets.MyFamilyPat }}@github.com/cgilliard/myfamily.git _coverage
          cd _coverage
          git config user.name "Pipelines-Bot"
          git checkout main
          ./fam clean; ./fam coverage --update-docs -s
          if [[ "$GITHUB_EVENT_NAME" == "schedule" || "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
             git config user.email "pipelinesbot.noreply@example.com"
             git config user.name "Pipelines-Bot"
             git commit -am "Pipelines-Bot: Updated repo (via build_docs script) Source Version is $GITHUB_SHA";
             git push https://${{ secrets.MyFamilyPat }}@github.com/cgilliard/myfamily.git
          fi
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [macos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check macOS Version
        run: sw_vers
      
      - name: Test MacOS Build
        run: |
          ./fam clean; ./fam
          # test -d ~/.fam/resources || { echo "Error: ~/.fam/resources directory does not exist"; exit 1; }
      - name: Run MacOS Tests (gcc)
        run: |
          ./fam clean; ./fam test --with-cc=gcc -s
      - name: Run MacOS Tests (clang)
        run: |
          ./fam clean; ./fam test --with-cc=clang -s
